//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.StuAssignmentMarks = new HashSet<StuAssignmentMark>();
        }
    
        public int AssignmentId { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public int SectionId { get; set; }
        public int CourseId { get; set; }
        public int TeacherId { get; set; }
        public int TotalMarks { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Section Section { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StuAssignmentMark> StuAssignmentMarks { get; set; }
    }
}
