//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int PayrollId { get; set; }
        public int TeacherId { get; set; }
        public decimal Salary { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public decimal Payable { get; set; }
        public int Status { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual LookUp LookUp { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
