//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Views.Teacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestion
    {
        public int PersonId { get; set; }
        public int SuggestionId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
    
        public virtual LookUp LookUp { get; set; }
        public virtual Person Person { get; set; }
    }
}
