//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Views.Teacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ttable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ttable()
        {
            this.TeacherTimetables = new HashSet<TeacherTimetable>();
        }
    
        public int Id { get; set; }
        public int TeacherId { get; set; }
        public string Day { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherTimetable> TeacherTimetables { get; set; }
    }
}
